name: Issue Forms Body Parser

on: 
 issues:
   types:
     - "opened"

jobs:
  addNewSpeaker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Speaker Information to file
      run: |
        Write-Host "What do we have?"
        gci -recurse
        $IssueBody =  "${{ github.event.issue.body }}"
        Write-Host $IssueBody 
        # $IssueBody | Out-File speakers/test.txt
      shell: pwsh   

    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: Beardy McBeardFace
        author_email: mrrobsewell@outlook.com
        message: 'The Beard says we have another speaker - This is an automated message'